MVC_CORE_PROJE/Areas/CalisanPanel/Controllers/CalisanController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_CORE_PROJE.Areas.CalisanPanel.Models.ViewModels;
using MVC_CORE_PROJE.Data;
using MVC_CORE_PROJE.Models;
using MVC_CORE_PROJE.Models.DTOs;
using ProjeOdevi.Services;
using System.Drawing;

namespace MVC_CORE_PROJE.Areas.CalisanPanel.Controllers
{
    [Area("CalisanPanel")]
    [Authorize(Roles = "Calisan,Admin")]

    public class CalisanController : Controller
    {
        private readonly KitapRepository _kitapRepository;
        private readonly KitapDBContext _context;
        private readonly IMapper _mapper;
        public CalisanController(KitapRepository kitapRepository, KitapDBContext context, IMapper mapper)
        {
            _kitapRepository = kitapRepository;
            _context = context;
            _mapper = mapper;
        }

        public IActionResult KitapListele()
        {
            var tumKitaplar = _kitapRepository.TumKitaplariListele().ToList();
            return View(tumKitaplar);
        }
        public IActionResult KitapEkle()
        {
            var yazarListesi = new SelectList(_context.Yazarlar.ToList(), "YazarID", "YazarAdi");
            var kategoriListesi = new SelectList(_context.Kategoriler.ToList(), "KategoriID", "KategoriAdi");
            var yayinEviListesi = new SelectList(_context.YayinEvleri.ToList(), "YayinEviID", "YayinEviAdi");
            ViewBag.Kategoriler = kategoriListesi;
            ViewBag.YayinEvleri = yayinEviListesi;
            ViewBag.Yazarlar = yazarListesi;
            return View();
        }
        [HttpPost]
        public IActionResult KitapEkle(KitapEkle_VM kitap, IFormFile ResimDosyasi, int[] yazarIDleri)
        {
            if (ModelState.IsValid && yazarIDleri.Length > 0)
            {
                Kitap_DTO yeniKitap = new Kitap_DTO();
                _mapper.Map(kitap, yeniKitap);

                if (ResimDosyasi != null)
                {
                    string path = "wwwroot/resimler/" + ResimDosyasi.FileName;
                    FileStream fs = new FileStream(path, FileMode.Create);
                    ResimDosyasi.CopyTo(fs);
                    fs.Close();
                    yeniKitap.KapakResmi = "/resimler/" + ResimDosyasi.FileName;
                }
                else
                {
                    yeniKitap.KapakResmi = "";
                }
                yeniKitap.YazarIDleri = yazarIDleri;
                _kitapRepository.Ekle(yeniKitap);
                return RedirectToAction("KitapListele");
            }

            ViewBag.Kategoriler = new SelectList(_context.Kategoriler.ToList(), "KategoriID", "KategoriAdi");
            ViewBag.YayinEvleri = new SelectList(_context.YayinEvleri.ToList(), "YayinEviID", "YayinEviAdi");
            ViewBag.Yazarlar = new SelectList(_context.Yazarlar.ToList(), "YazarID", "YazarAdi");

            return View(kitap);
        }

        public IActionResult KitapGuncelle(int id)
        {
            var yazarlar = _context.Yazarlar
                   .Select(y => new SelectListItem
                   {
                       Value = y.YazarID.ToString(),
                       Text = y.YazarAdi
                   }).ToList(); var kategoriListesi = new SelectList(_context.Kategoriler.ToList(), "KategoriID", "KategoriAdi");

            var yayinEviListesi = new SelectList(_context.YayinEvleri.ToList(), "YayinEviID", "YayinEviAdi");
            ViewBag.Kategoriler = kategoriListesi;
            ViewBag.YayinEvleri = yayinEviListesi;
            ViewBag.Yazarlar = yazarlar ?? new List<SelectListItem>();


            var kitap = _context.Kitaplar
                 .Include(b => b.Kategori)
                 .Include(b => b.YayinEvi)
                 .Include(b => b.Kitap_Yazarlar).ThenInclude(x => x.Yazar).FirstOrDefault(x => x.KitapID == id);

            var selectedAuthorIds = kitap.Kitap_Yazarlar.Select(ky => ky.YazarID).ToList();
            ViewBag.SelectedAuthorIds = selectedAuthorIds;

            return View(kitap);
        }

        [HttpPost]
        public IActionResult KitapGuncelle(Kitap kitap, IFormFile ResimDosyasi, List<int> yazarIDleri)
        {
            if (kitap != null)
            {
                _kitapRepository.UpdateBook(kitap, ResimDosyasi, yazarIDleri);
            }
            return RedirectToAction("KitapListele");
        }
        [HttpGet]
        public IActionResult KitapSil(int id)
        {
            var kitap = _context.Kitaplar
                 .Include(b => b.Kategori)
                 .Include(b => b.YayinEvi)
                 .Include(b => b.Kitap_Yazarlar).ThenInclude(x => x.Yazar).FirstOrDefault(x => x.KitapID == id);
            ViewBag.Kategoriler = kitap.Kategori.KategoriAdi;
            ViewBag.YayinEvleri = kitap.YayinEvi.YayinEviAdi;
            ViewBag.Yazarlar = kitap.Kitap_Yazarlar;
            return View(kitap);

        }
        [HttpPost]
        public IActionResult KitapSil(Kitap kitap)
        {
            var silinenKitap = _kitapRepository.Ara(kitap.KitapID);
            if (silinenKitap != null)
            {
                _kitapRepository.Sil(silinenKitap.KitapID);
            }
            return RedirectToAction("KitapListele");
        }

        public IActionResult KitapDetay(int id)
        {
            var kitap = _context.Kitaplar
                 .Include(b => b.Kategori)
                 .Include(b => b.YayinEvi)
                 .Include(b => b.Kitap_Yazarlar).ThenInclude(x => x.Yazar).FirstOrDefault(x => x.KitapID == id);

            return View(kitap);
        }

    }

}

MVC_CORE_PROJE/Areas/CalisanPanel/Views/Calisan/KitapDetay.cshtml
@model Kitap
@{
    ViewData["Title"] = "Kitap Detay";
}

<h1 class="text-center my-4">@ViewData["Title"]</h1>
<hr />
<div class="container mt-4">
    <div class="row">
        <div class="col-md-8 offset-md-2 bg-light p-4 rounded shadow">
            <dl class="row">
                <dt class="col-sm-4 font-weight-bold">
                    Kitap Adı
                </dt>
                <dd class="col-sm-8">
                    @Model.KitapAdi
                </dd>

                <dt class="col-sm-4 font-weight-bold">
                    Fiyat
                </dt>
                <dd class="col-sm-8">
                    @Model.Fiyat.ToString("C")
                </dd>

                <dt class="col-sm-4 font-weight-bold">
                    Stok
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.Stok)
                </dd>

                <dt class="col-sm-4 font-weight-bold">
                    Kapak Resmi
                </dt>
                <dd class="col-sm-8">
                    <img src="@Model.KapakResmi" class="img-fluid rounded border" style="max-width: 180px; max-height: 200px;" alt="@Model.KitapAdi" />
                </dd>

                <dt class="col-sm-4 font-weight-bold">
                    Yazar Adı
                </dt>
                <dd class="col-sm-8">
                    @string.Join(", ", Model.Kitap_Yazarlar.Select(y => y.Yazar.YazarAdi))
                </dd>

                <dt class="col-sm-4 font-weight-bold">
                    Yayın Evi Adı
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.YayinEvi.YayinEviAdi)
                </dd>

                <dt class="col-sm-4 font-weight-bold">
                    Kategori Adı
                </dt>
                <dd class="col-sm-8">
                    @Html.DisplayFor(model => model.Kategori.KategoriAdi)
                </dd>
            </dl>
        </div>
    </div>
</div>

<div class="text-center mt-4">
    @Html.ActionLink("Güncelle", "KitapGuncelle", new { id = Model.KitapID }, new { @class = "btn btn-primary" })
    <a asp-action="KitapListele" class="btn btn-secondary">Listeye Dön</a>
</div>

MVC_CORE_PROJE/Areas/CalisanPanel/Views/Calisan/KitapEkle.cshtml
@using MVC_CORE_PROJE.Areas.CalisanPanel.Models.ViewModels
@model KitapEkle_VM

@{
    ViewData["Title"] = "Kitap Ekle";
}

<h1 class="text-center my-4">Kitap Ekle</h1>
<hr />
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <form asp-action="KitapEkle" method="post" enctype="multipart/form-data" class="bg-light p-4 rounded shadow">
                <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>

                <div class="form-group">
                    <label asp-for="KitapAdi" class="control-label"></label>
                    <input asp-for="KitapAdi" class="form-control" placeholder="Kitap Adını Girin" />
                    <span asp-validation-for="KitapAdi" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Fiyat" class="control-label"></label>
                    <input type="number" asp-for="Fiyat" class="form-control" placeholder="Fiyatı Girin" />
                    <span asp-validation-for="Fiyat" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Stok" class="control-label"></label>
                    <input type="number" asp-for="Stok" class="form-control" placeholder="Stok Miktarını Girin" />
                    <span asp-validation-for="Stok" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="KapakResmi" class="control-label"></label>
                    <input name="ResimDosyasi" type="file" class="form-control" />
                    <span asp-validation-for="KapakResmi" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="YazarIDleri" class="control-label">Yazar Adı</label>
                    <div class="form-check">
                        @if (ViewBag.Yazarlar != null)
                        {
                            @foreach (var item in ViewBag.Yazarlar)
                            {
                                <div class="form-check">
                                    <input type="checkbox" class="form-check-input" name="yazarIDleri" value="@item.Value" id="yazar_@item.Value" />
                                    <label class="form-check-label" for="yazar_@item.Value">@item.Text</label>
                                </div>
                            }
                        }
                        <span asp-validation-for="YazarIDleri" class="text-danger"></span>

                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="YayinEviID" class="control-label">Yayın Evi Adı</label>
                    <select asp-for="YayinEviID" asp-items="@ViewBag.YayinEvleri" class="form-control"></select>
                    <span asp-validation-for="YayinEviID" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="KategoriID" class="control-label">Kategori Adı</label>
                    <select asp-for="KategoriID" asp-items="@ViewBag.Kategoriler" class="form-control"></select>
                    <span asp-validation-for="KategoriID" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Ekle" class="btn btn-primary btn-block" />
                    <a asp-action="KitapListele" class="btn btn-secondary">Listeye Dön</a>
                </div>
            </form>
        </div>
    </div>
</div>

MVC_CORE_PROJE/Areas/CalisanPanel/Views/Calisan/KitapGuncelle.cshtml
@model MVC_CORE_PROJE.Models.Kitap

@{
    ViewData["Title"] = "KitapGuncelle";
}

<h1 class="text-center my-4">Kitap Güncelleme</h1>
<hr />
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <form asp-action="KitapGuncelle" method="post" enctype="multipart/form-data" class="bg-light p-4 rounded shadow">
                <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>

                <div class="form-group">
                    <input asp-for="KitapID" hidden class="form-control" />
                </div>

                <div class="form-group">
                    <label asp-for="KitapAdi" class="control-label">Kitap Adı</label>
                    <input asp-for="KitapAdi" value="@Model.KitapAdi" class="form-control" placeholder="Kitap Adını Girin" />
                    <span asp-validation-for="KitapAdi" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Fiyat" class="control-label">Fiyat</label>
                    <input type="number" asp-for="Fiyat" class="form-control" placeholder="Fiyatı Girin" />
                    <span asp-validation-for="Fiyat" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Stok" class="control-label">Stok</label>
                    <input type="number" asp-for="Stok" class="form-control" placeholder="Stok Miktarını Girin" />
                    <span asp-validation-for="Stok" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="KapakResmi" class="control-label">Kapak Resmi</label>
                    <input type="file" name="ResimDosyasi" class="form-control" />
                    <span asp-validation-for="KapakResmi" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label class="control-label">Yazar Adı</label>
                    <div class="form-check">
                        @foreach (var item in ViewBag.Yazarlar)
                        {
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" name="yazarIDleri" value="@item.Value" @(ViewBag.SelectedAuthorIds.Contains(int.Parse(item.Value)) ? "checked" : "") />
                                <label class="form-check-label">@item.Text</label>
                            </div>
                        }
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="YayinEviID" class="control-label">Yayın Evi Adı</label>
                    <select asp-for="YayinEviID" asp-items="@ViewBag.YayinEvleri" class="form-control"></select>
                    <span asp-validation-for="YayinEviID" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="KategoriID" class="control-label">Kategori Adı</label>
                    <select asp-for="KategoriID" asp-items="@ViewBag.Kategoriler" class="form-control"></select>
                    <span asp-validation-for="KategoriID" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Kaydet" class="btn btn-primary btn-block" />
                    <a asp-action="KitapListele" class="btn btn-secondary">Listeye Geri Dön</a>
                </div>
            </form>
        </div>
    </div>
</div>

MVC_CORE_PROJE/Areas/CalisanPanel/Views/Calisan/KitapListele.cshtml
@model IEnumerable<dynamic>

<h3 style="text-align: center; color: #333;">TÜM KİTAPLAR</h3>

<div class="button-container">
    <button type="button" class="btn btn-warning" onclick="location.href='@Url.Action("KitapEkle")'">Yeni Kitap Ekle</button>
    @if (User.IsInRole("Admin"))
    {
        <button type="button" class="btn btn-secondary" onclick="location.href='@Url.Action("Index", "Admin", new { area = "AdminPanel" })'"> Rapor Sayfasına Dön</button>
    }
</div>

<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;
        margin: 20px;
    }

    table {
        width: 100%;
        border-collapse: collapse;
        margin: 20px 0;
        box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
    }

    th, td {
        padding: 12px;
        text-align: left;
        border-bottom: 1px solid #ddd;
        background-color: #fff;
    }

    th {
        background-color: #4CAF50;
        color: white;
    }

    tr:hover {
        background-color: #f1f1f1;
    }


    img {
        width: 40px;
        height: 60px;
        object-fit: cover;
        border-radius: 4px;
    }

    .button-container {
        display: flex;
        gap: 10px;
    }

    .btn {
        flex: 1;
    }
</style>

<table>
    <thead>
        <tr>
            @*  <th>Kitap ID</th> *@
            <th>Kitap Adı</th>
            <th>Fiyat</th>
            <th>Kapak Resmi</th>
            <th>Kategori</th>
            <th>Yazar</th>
            <th>Yayın Evi</th>
            <th>Stok</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var kitap in Model)
        {
            <tr>
                <td>@kitap.KitapAdi</td>
                <td>@kitap.Fiyat.ToString("C")</td>
                <td><img src="@kitap.KapakResmi" alt="Kapak Resmi" /></td>
                <td>@kitap.Kategori</td>
                <td>@kitap.Yazar</td>
                <td>@kitap.YayinEvi</td>
                <td>@kitap.Stok</td>
                <td>
                    <div class="button-container">
                        <button type="button" class="btn btn-success" onclick="location.href='@Url.Action("KitapGuncelle", new { id = kitap.KitapID })'">Güncelle</button>
                        <button type="button" class="btn btn-info" onclick="location.href='@Url.Action("KitapDetay", new { id = kitap.KitapID })'">Detay</button>
                        <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("KitapSil", new { id = kitap.KitapID })'">Sil</button>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

MVC_CORE_PROJE/Areas/CalisanPanel/Views/Calisan/KitapSil.cshtml
@model MVC_CORE_PROJE.Models.Kitap
@{
    ViewData["Title"] = "KitapSil";
}
<h3 class="text-center">Kitabı Silmek İstediğinize Emin Misiniz?</h3>
<div class="container mt-4">
    <hr />
    <form asp-area="CalisanPanel" asp-controller="Calisan" asp-action="KitapSil" method="post">
        <input type="hidden" name="KitapID" value="@Model.KitapID" />

        <div class="row">
            <div class="col-sm-4">
                <div class="border p-2 mb-3 text-center">
                    <strong>@Html.DisplayNameFor(model => model.KitapAdi)</strong><br />
                    @Html.DisplayFor(model => model.KitapAdi)
                </div>
            </div>
            <div class="col-sm-4">
                <div class="border p-2 mb-3 text-center">
                    <strong>@Html.DisplayNameFor(model => model.Fiyat)</strong><br />
                    @Model.Fiyat.ToString("C")
                </div>
            </div>
            <div class="col-sm-4">
                <div class="border p-2 mb-3 text-center">
                    <strong>@Html.DisplayNameFor(model => model.Stok)</strong><br />
                    @Html.DisplayFor(model => model.Stok)
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-4">
                <div class="border p-2 mb-3 text-center">
                    <strong>Yazar Adı</strong><br />
                    @string.Join(", ", Model.Kitap_Yazarlar.Select(y => y.Yazar.YazarAdi))
                </div>
            </div>
            <div class="col-sm-4">
                <div class="border p-2 mb-3 text-center">
                    <strong>Yayın Evi Adı</strong><br />
                    @Html.DisplayFor(model => model.YayinEvi.YayinEviAdi)
                </div>
            </div>
            <div class="col-sm-4">
                <div class="border p-2 mb-3 text-center">
                    <strong>Kategori Adı</strong><br />
                    @Html.DisplayFor(model => model.Kategori.KategoriAdi)
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12 text-center">
                <div class="border p-2 mb-3">
                    <strong>@Html.DisplayNameFor(model => model.KapakResmi)</strong><br />
                    <img src="@Model.KapakResmi" style="max-height: 200px; max-width: 180px;" />
                </div>
            </div>
        </div>

        <div class="text-center mt-3">
            <input type="submit" value="Sil" class="btn btn-danger" />
            <a asp-action="KitapListele" class="btn btn-secondary">Listeye Geri Dön</a>
        </div>
    </form>
</div>